---
ID: "072abd79-602f-473b-8c60-cb8bd34ba4c6"
Parent: "7e080a41-83f2-48ae-8fdc-a204dadd37b5"
Template: "7e080a41-83f2-48ae-8fdc-a204dadd37b5"
Path: /sitecore/templates/Foundation/Sloth/Sitecore Sloth/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211126T235547Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a0555bce-7220-4221-9033-04cea44bb79a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d20d742f-44f4-43b3-866f-baf82e40c5f7"
      Hint: Enabled
      Value: 1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211126T235552Z
